[project]
name = "thanakan-oauth"
version = "0.2.0"
description = "Thai bank OAuth API clients (SCB, KBank)"
readme = "README.md"
authors = [
    { name = "ben", email = "me@nutchanon.org" }
]
requires-python = ">=3.12"
license = {text = "Sustainable Use License"}
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pydantic>=2.0",
    "httpx>=0.22",
    "httpx-auth>=0.14",
    "furl>=2.1",
    "loguru>=0.6",
    "pytz",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
